# Check advisories, bans and sources explicitly. A project license policy has
# not been selected; do not invoke the licenses check as an implicit default.
[graph]
all-features = true

[advisories]
db-urls = ["https://github.com/RustSec/advisory-db"]
yanked = "deny"
unmaintained = "all"
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = true

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
required-git-spec = "rev"
