packages:
  - apps/*
  - packages/*
  - providers/claude
  - providers/omp
  - providers/codex
  - providers/acp
  - plugins/opencode
verifyDepsBeforeRun: error
allowBuilds:
  nx: true
  electron-winstaller: false
  esbuild: false
  onnxruntime-node: false
  protobufjs: false
minimumReleaseAgeExclude:
  - electron-vite@6.0.0-beta.3
  - '@tanstack/react-router@1.170.40'
  - '@tanstack/router-core@1.171.33'
  - '@tanstack/hotkeys@0.10.1'
  - '@tanstack/react-hotkeys@0.12.1'
  - '@effect/tsgo-darwin-arm64@0.47.1'
  - '@effect/tsgo-darwin-x64@0.47.1'
  - '@effect/tsgo-linux-arm64@0.47.1'
  - '@effect/tsgo-linux-arm@0.47.1'
  - '@effect/tsgo-linux-x64@0.47.1'
  - '@effect/tsgo-win32-arm64@0.47.1'
  - '@effect/tsgo-win32-x64@0.47.1'
  - '@effect/tsgo@0.47.1'
