import {
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AtSign,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsUpDown,
  CircleAlert,
  CircleCheck,
  CirclePause,
  CircleX,
  CodeXml,
  Columns2,
  Copy,
  Ellipsis,
  Eraser,
  ExternalLink,
  File,
  FileCode,
  FileDiff,
  Folder,
  FolderGit2,
  FolderOpen,
  FolderPlus,
  Folders,
  GitBranch,
  GitFork,
  Globe,
  Inbox,
  Info,
  LoaderCircle,
  Lock,
  MessageSquare,
  PanelLeft,
  PanelRight,
  PanelsTopLeft,
  Plus,
  RotateCcw,
  RotateCw,
  Rows2,
  Search,
  Settings,
  Shield,
  ShieldAlert,
  Square,
  SquarePen,
  SquareTerminal,
  Sun,
  SunMoon,
  TriangleAlert,
  Unplug,
  UserRound,
  X,
} from 'lucide-react'

// Every icon the app draws, by what it means. Code asks for `conversation`, never for
// `MessageSquare`, so one idea always has one icon and swapping an icon is a one-line change here.
// Names follow CONTEXT.md. Add an icon here before using it; lint refuses lucide-react imports
// anywhere else outside the kit (components/ui).

/** Things: what ADE shows. */
const things = {
  activity: Inbox,
  branch: GitBranch,
  browser: Globe,
  conversation: MessageSquare,
  diff: FileDiff,
  file: File,
  fileCode: FileCode,
  folder: Folder,
  folderOpen: FolderOpen,
  profile: UserRound,
  project: FolderGit2,
  projects: Folders,
  settings: Settings,
  terminal: SquareTerminal,
  workspace: PanelsTopLeft,
} as const

/** Actions: what a control does. */
const actions = {
  addProject: FolderPlus,
  attach: Plus,
  back: ArrowLeft,
  clear: Eraser,
  close: X,
  collapse: ChevronDown,
  copy: Copy,
  devtools: CodeXml,
  expand: ChevronRight,
  fork: GitFork,
  forward: ArrowRight,
  mention: AtSign,
  more: Ellipsis,
  new: Plus,
  newConversation: SquarePen,
  openExternal: ExternalLink,
  push: ArrowUp,
  reload: RotateCw,
  restart: RotateCcw,
  search: Search,
  select: ChevronsUpDown,
  send: ArrowUp,
  splitDown: Rows2,
  splitRight: Columns2,
  stop: Square,
  themeLight: Sun,
  themeSystem: SunMoon,
  toggleLeftSidebar: PanelLeft,
  toggleRightSidebar: PanelRight,
} as const

/** Outcomes and states. Their colour belongs to the Status component, not to the icon. */
const states = {
  approval: ShieldAlert,
  disconnected: Unplug,
  done: CircleCheck,
  error: CircleX,
  failed: CircleAlert,
  info: Info,
  interrupted: CirclePause,
  loading: LoaderCircle,
  locked: Lock,
  permission: Shield,
  selected: Check,
  warning: TriangleAlert,
} as const

export const icons = { ...things, ...actions, ...states }

export type IconName = keyof typeof icons
